import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { RubricRow } from '@/components/EditableRubric';
import { RubricFormData } from '@/components/RubricForm';
import { format } from 'date-fns';
export const exportRubricToPDF = (data: RubricRow[], metadata: RubricFormData) => {
  const doc = new jsPDF('l', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  // Header
  doc.setFontSize(24);
  doc.setTextColor(79, 70, 229); // Brand Indigo
  doc.text(metadata.assignmentName, 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  let metaLine = `Subject: ${metadata.subject} | Grade: ${metadata.gradeLevel} | Scale: ${metadata.scale}-pt`;
  if (metadata.teacherName) {
    metaLine = `Teacher: ${metadata.teacherName} | ` + metaLine;
  }
  doc.text(metaLine, 14, 28);
  const headers = [['Criterion', ...Array.from({ length: metadata.scale }, (_, i) => `Level ${metadata.scale - i}`)]];
  const body = data.map(row => [
    row.criterion,
    ...row.levels
  ]);
  autoTable(doc, {
    startY: 35,
    head: headers,
    body: body,
    theme: 'grid',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontSize: 11,
      fontStyle: 'bold',
      halign: 'center'
    },
    styles: {
      fontSize: 10,
      cellPadding: 6,
      overflow: 'linebreak',
      valign: 'middle'
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 45 },
      // Dynamically center all level columns
      ...Object.fromEntries(
        Array.from({ length: metadata.scale }).map((_, i) => [i + 1, { halign: 'left' }])
      )
    },
    margin: { bottom: 20 }
  });
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by LinearEd on ${format(new Date(), 'MMMM d, yyyy')}`, 14, footerY);
  doc.text(`Page 1 of 1`, pageWidth - 25, footerY);
  // Sanitize filename
  const safeName = metadata.assignmentName
    .replace(/[^a-z0-9]/gi, '_')
    .toLowerCase()
    .slice(0, 50);
  doc.save(`${safeName}_LinearEd_Rubric.pdf`);
};