import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { RubricRow } from '@/components/EditableRubric';
import { RubricFormData } from '@/components/RubricForm';
import { format } from 'date-fns';
export const exportRubricToPDF = (data: RubricRow[], metadata: RubricFormData) => {
  const doc = new jsPDF('l', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  // Header Styling
  const titleText = metadata.assignmentName.length > 50
    ? metadata.assignmentName.substring(0, 47) + '...'
    : metadata.assignmentName;
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229); // Brand Indigo
  doc.text(titleText, 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100);
  let metaLine = `Subject: ${metadata.subject} | Grade: ${metadata.gradeLevel} | Scale: ${metadata.scale}-pt`;
  if (metadata.teacherName) {
    metaLine = `Teacher: ${metadata.teacherName} | ` + metaLine;
  }
  doc.text(metaLine, 14, 28);
  const headers = [['Criterion', ...Array.from({ length: metadata.scale }, (_, i) => `Level ${metadata.scale - i}`)]];
  const body = data.map(row => [
    row.criterion,
    ...row.levels
  ]);
  autoTable(doc, {
    startY: 35,
    head: headers,
    body: body,
    theme: 'grid',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontSize: 10,
      fontStyle: 'bold',
      halign: 'center',
      minCellHeight: 12,
      valign: 'middle'
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      overflow: 'linebreak',
      valign: 'top',
      lineColor: [220, 220, 220],
      lineWidth: 0.1,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 40 },
      ...Object.fromEntries(
        Array.from({ length: metadata.scale }).map((_, i) => [i + 1, { halign: 'left', cellWidth: 'auto' }])
      )
    },
    margin: { bottom: 20, left: 14, right: 14 },
    didDrawPage: (data) => {
      // Footer on every page
      const footerY = pageHeight - 10;
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Generated by LinearEd on ${format(new Date(), 'MMMM d, yyyy')}`, 14, footerY);
      // Fix: Use doc.getNumberOfPages() instead of doc.internal.getNumberOfPages()
      const pageNumber = doc.getNumberOfPages();
      doc.text(`Page ${pageNumber}`, pageWidth - 20, footerY);
    }
  });
  // Sanitize filename
  const safeName = metadata.assignmentName
    .replace(/[^a-z0-9]/gi, '_')
    .toLowerCase()
    .slice(0, 50);
  doc.save(`${safeName}_LinearEd_Rubric.pdf`);
};